### ISSUE TITLE
squashfs tradeoffs

### ISSUE THREAD

**Issue by probonopd** [CanDIG/images_bakeoff#1]
When measuring AppImage performance, be aware that Type 2 AppImages use squashfs which can be configured along a wide range of speed vs. compressed filesize. Depending on what you value more, you might want to tune its settings a bit [here](https://github.com/probonopd/AppImageKit/blob/90ee36655337ce4a94c260f3525e6160e8ccd370/appimagetool.c#L122-L129).

Also see https://jonathancarter.org/2015/04/06/squashfs-performance-testing/.

**Comment by ljdursi** [comment]
Interesting, thanks - I'll leave this open until we decide how we're handling AppImages.
